report_list = ['Annual Consolidated OAG audit reports 2018',
 'Annual Consolidated OAG audit reports 2019',
 'Annual Consolidated OAG audit reports 2020',
 'Annual Consolidated OAG audit reports 2021',
 'Annual Consolidated OAG audit reports 2022',
 'Gulu DLG Report of Auditor General 2018',
 'Gulu DLG Report of Auditor General 2019',
 'Gulu DLG Report of Auditor General 2020',
 'Gulu DLG Report of Auditor General 2021',
 'Gulu DLG Report of Auditor General 2022',
 'Kalangala DLG Report of Auditor General 2018',
 'Kalangala DLG Report of Auditor General 2019',
 'Kalangala DLG Report of Auditor General 2020',
 'Kalangala DLG Report of Auditor General 2021',
 'Kalangala DLG Report of Auditor General 2022',
 'KCCA Report of Auditor General 2018',
 'KCCA Report of Auditor General 2019',
 'KCCA Report of Auditor General 2020',
 'KCCA Report of Auditor General 2021',
 'KCCA Report of Auditor General 2022',
 'MAAIF Report of Auditor General 2019',
 'MAAIF Report of Auditor General 2021',
 'MAAIF Report of Auditor General 2022',
 'MAAIF Report of Auditor General 2020',
 'MWTS Report of Auditor General 2019',
 'MWTS Report of Auditor General 2020',
 'MWTS Report of Auditor General 2021',
 'MWTS Report of Auditor General 2022']

files = {'Consolidated':{'Consolidated Annnual Report':['Annual Consolidated OAG audit reports 2018',
                                                        'Annual Consolidated OAG audit reports 2019',
                                                        'Annual Consolidated OAG audit reports 2020',
                                                        'Annual Consolidated OAG audit reports 2021',
                                                        'Annual Consolidated OAG audit reports 2022']},
        'District':{'Gulu':['Gulu DLG Report of Auditor General 2018',
                            'Gulu DLG Report of Auditor General 2019',
                            'Gulu DLG Report of Auditor General 2020',
                            'Gulu DLG Report of Auditor General 2021',
                            'Gulu DLG Report of Auditor General 2022'],
                    'Kalangala':['Kalangala DLG Report of Auditor General 2018',
                                 'Kalangala DLG Report of Auditor General 2019',
                                 'Kalangala DLG Report of Auditor General 2020',
                                 'Kalangala DLG Report of Auditor General 2021',
                                 'Kalangala DLG Report of Auditor General 2022'],
                    'Kampala':['KCCA Report of Auditor General 2018',
                               'KCCA Report of Auditor General 2019',
                               'KCCA Report of Auditor General 2020',
                               'KCCA Report of Auditor General 2021',
                               'KCCA Report of Auditor General 2022']},
        'Ministry':{'Agriculture, Animal Industry and Fisheries':['MAAIF Report of Auditor General 2019',
                                                                  'MAAIF Report of Auditor General 2020',
                                                                  'MAAIF Report of Auditor General 2021',
                                                                  'MAAIF Report of Auditor General 2022'],
                    'Works and Transport':['MWTS Report of Auditor General 2019',
                                           'MWTS Report of Auditor General 2020',
                                           'MWTS Report of Auditor General 2021',
                                           'MWTS Report of Auditor General 2022']
                                           }
        }